version: '2'
services:
  doby:
#    image: dob
    build: .
    ports:
      - 7999:7999
    volumes:
      - ./credentials.yml:/etc/dob/credentials.yml:ro
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - redis
  redis:
    image: redis