version: '2.1'
services:
  doby:
    #    image: dob
    build: .
    ports:
    - 7999:7999
    volumes:
    - ./credentials.yml:/etc/dob/credentials.yml:ro
    environment:
    - PYTHONUNBUFFERED=0
    - redis=redis
    depends_on:
    - redis
    links:
    - redis:redis
  redis:
    image: redis
