filtered_words:
  - a
  - ante
  - bajo
  - cabe
  - con
  - contra
  - de
  - desde
  - en
  - entre
  - hacia
  - hasta
  - para
  - por
  - según
  - sin
  - so
  - sobre
  - tras
  - durante
  - mediante
  - versus
  - vía
  - la
  - el
  - los
  - un
  - al