clarin_filtrado = ["https://www.clarin.com/rss/politica/",
                   "https://www.clarin.com/rss/lo-ultimo/",
                   "https://www.clarin.com/rss/sociedad/",
                   "https://www.clarin.com/rss/mundo/",
                   "https://www.clarin.com/rss/policiales/",
                   "	https://www.clarin.com/rss/ciudades/",
                   "https://www.clarin.com/rss/cultura/",
                   "https://www.clarin.com/rss/deportes/futbol/"]

clarin_completo = ["https://www.clarin.com/rss/arq/",
                   "https://www.clarin.com/rss/br/",
                   "https://www.clarin.com/rss/buena-vida/",
                   "https://www.clarin.com/rss/cartas_al_pais/",
                   "https://www.clarin.com/rss/ciudades/",
                   "https://www.clarin.com/rss/cultura/",
                   "https://www.clarin.com/rss/deautos/",
                   "https://www.clarin.com/rss/deportes/",
                   "https://www.clarin.com/rss/deportes/ascenso/",
                   "https://www.clarin.com/rss/deportes/automovilismo/",
                   "https://www.clarin.com/rss/deportes/basquet/",
                   "https://www.clarin.com/rss/deportes/boxeo/",
                   "https://www.clarin.com/rss/deportes/futbol-internacional/",
                   "https://www.clarin.com/rss/deportes/futbol/",
                   "https://www.clarin.com/rss/deportes/hockey/",
                   "https://www.clarin.com/rss/deportes/messi/",
                   "https://www.clarin.com/rss/deportes/polideportivo/",
                   "https://www.clarin.com/rss/deportes/rugby/",
                   "https://www.clarin.com/rss/deportes/tenis/",
                   "https://www.clarin.com/rss/deportes/turf/",
                   "https://www.clarin.com/rss/entremujeres/",
                   "https://www.clarin.com/rss/extrashow/",
                   "https://www.clarin.com/rss/extrashow/cine/",
                   "https://www.clarin.com/rss/extrashow/fama/",
                   "https://www.clarin.com/rss/extrashow/musica/",
                   "https://www.clarin.com/rss/extrashow/teatro/",
                   "https://www.clarin.com/rss/extrashow/tv/",
                   "https://www.clarin.com/rss/ieco/",
                   "https://www.clarin.com/rss/lo-ultimo/",
                   "https://www.clarin.com/rss/mundo/",
                   "https://www.clarin.com/rss/next/",
                   "https://www.clarin.com/rss/opinion/",
                   "https://www.clarin.com/rss/policiales/",
                   "https://www.clarin.com/rss/politica/",
                   "https://www.clarin.com/rss/rn/",
                   "https://www.clarin.com/rss/rural/",
                   "https://www.clarin.com/rss/si/",
                   "https://www.clarin.com/rss/sociedad/",
                   "https://www.clarin.com/rss/todoviajes/",
                   "https://www.clarin.com/rss/viva/"]

la_nacion_filtrado = ["http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7775"]

la_nacion_completo = ["http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1344",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1348",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=28",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=337",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=347",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=371",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=421",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=494",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=504",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6373",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6734",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7774",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7775",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/origen=1",
                      "http://contenidos.lanacion.com.ar/herramientas/rss/origen=2"]

# rotisimo, no se porque no lo toma. Ni lo puede leer.
pagina_doce = ["https://www.pagina12.com.ar/rss/secciones/el-pais/notas",
               "https://www.pagina12.com.ar/rss/secciones/economia/notas",
               "https://www.pagina12.com.ar/rss/secciones/sociedad/notas",
               "https://www.pagina12.com.ar/rss/secciones/el-mundo/notas",
               "https://www.pagina12.com.ar/rss/secciones/deportes/notas",
               "https://www.pagina12.com.ar/rss/secciones/cultura/notas"]

perfil = ["http://www.perfil.com/rss/ultimomomento.xml",
          "http://www.perfil.com/rss/politica.xml",
          "http://www.perfil.com/rss/policia.xml",
          "http://www.perfil.com/rss/internacional.xml",
          "http://www.perfil.com/rss/economia.xml",
          "http://www.perfil.com/rss/deportes.xml"]

infobae = ["http://www.infobae.com/argentina-rss.xml"]

la_razon = ["http://www.la-razon.com/rss/latest/?contentType=NWS",
            "http://www.la-razon.com/rss/sociedad/",
            "http://www.la-razon.com/rss/opinion/editorial/",
            "http://www.la-razon.com/rss/suplementos/informe/",
            "http://www.la-razon.com/rss/suplementos/animal_politico/",
            "http://www.la-razon.com/rss/sociales/",
            "http://www.la-razon.com/rss/nacional/seguridad_nacional/",
            "http://www.la-razon.com/rss/mundo/",
            "http://www.la-razon.com/rss/economia/"]

minuto_uno = ["http://www.minutouno.com/rss/mundo.xml",
              "http://www.minutouno.com/rss/principal.xml",
              "http://www.minutouno.com/rss/sociedad.xml",
              "http://www.minutouno.com/rss/economia.xml",
              "http://www.minutouno.com/rss/politica.xml",
              "http://www.minutouno.com/rss/tecnologia.xml",
              "http://www.minutouno.com/rss/deportes.xml",
              "http://www.minutouno.com/rss/negocios.xml"]

telam = ["http://www.telam.com.ar/rss2/ultimasnoticias.xml",
         "http://www.telam.com.ar/rss2/politica.xml",
         "http://www.telam.com.ar/rss2/economia.xml",
         "http://www.telam.com.ar/rss2/sociedad.xml",
         "http://www.telam.com.ar/rss2/deportes.xml",
         "http://www.telam.com.ar/rss2/policiales.xml",
         "http://www.telam.com.ar/rss2/cultura.xml",
         "http://www.telam.com.ar/rss2/educacion.xml"]

rss = {"Clarin": clarin_filtrado, "La Nacion": la_nacion_filtrado,
       "perfil": perfil, "Infobae": infobae,
       "la Razon": la_razon, "Minuto Uno": minuto_uno,
       "Telam": telam}
